### ISSUE TITLE
Feedbacks

### ISSUE THREAD

**Issue by LadanTazik** [data301-2020-winter2/course-project-group_1004#2]
#high priority

- [x] Include all tasks in one single file names milestone 2
# low priority
- [x] EDA in Quinn's file doesn't have titles for the plot, add  titles to your plots, it would be more self-explanatory 
- [x] Avoid unnecessary heading and highlights in you report

**Comment by Soosi18** [comment]
- Added new notebook called 'milestone 2.ipynb' at '/analysis/submitted' which contains all tasks in one file (feedback 1)
- Quinn added titles to her plots in her EDA (feedback 2)
- Removed many unnecessary headings and titles in 'Research_Analysis' document. This change is also present in the 'milestone 2.ipynb' file from feedback 1. (feedback 3)
